"""add_missing_username_column

Revision ID: 06dbd28ca974
Revises: fix_model_cons_001
Create Date: 2026-04-27 02:58:48.004459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06dbd28ca974'
down_revision = 'fix_model_cons_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_sets_id'), 'flashcard_sets', ['id'], unique=False)
    op.create_table('student_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_grades_id'), 'student_grades', ['id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_questions_id'), 'test_questions', ['id'], unique=False)
    op.drop_index('ix_external_searches_id', table_name='external_searches')
    op.drop_table('external_searches')
    op.drop_index('ix_activity_logs_id', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_highlights_id', table_name='highlights')
    op.drop_table('highlights')
    op.drop_index('ix_calculator_logs_id', table_name='calculator_logs')
    op.drop_table('calculator_logs')
    op.drop_index('idx_flashcard_progress_flashcard', table_name='flashcard_progress')
    op.drop_index('idx_flashcard_progress_user', table_name='flashcard_progress')
    op.drop_table('flashcard_progress')
    op.drop_index('ix_quiz_results_id', table_name='quiz_results')
    op.drop_table('quiz_results')
    op.drop_index('ix_plagiarism_reports_id', table_name='plagiarism_reports')
    op.drop_table('plagiarism_reports')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_quizzes_id', table_name='quizzes')
    op.drop_table('quizzes')
    op.add_column('discussions', sa.Column('is_question', sa.Boolean(), nullable=True))
    op.add_column('discussions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_shares', sa.Column('shared_by_id', sa.Integer(), nullable=False))
    op.add_column('document_shares', sa.Column('shared_to_id', sa.Integer(), nullable=True))
    op.add_column('document_shares', sa.Column('message', sa.Text(), nullable=True))
    op.alter_column('document_shares', 'permission',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('document_shares_shared_with_user_id_fkey', 'document_shares', type_='foreignkey')
    op.create_foreign_key(None, 'document_shares', 'users', ['shared_to_id'], ['id'])
    op.create_foreign_key(None, 'document_shares', 'users', ['shared_by_id'], ['id'])
    op.drop_column('document_shares', 'shared_with_user_id')
    op.drop_column('document_shares', 'access_count')
    op.drop_column('document_shares', 'expires_at')
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_index('idx_document_public', table_name='documents')
    op.drop_index('idx_document_subject', table_name='documents')
    op.drop_index('idx_document_uploader', table_name='documents')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'file_url')
    op.add_column('flashcards', sa.Column('set_id', sa.Integer(), nullable=False))
    op.add_column('flashcards', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('flashcards_document_id_fkey', 'flashcards', type_='foreignkey')
    op.drop_constraint('flashcards_user_id_fkey', 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'flashcard_sets', ['set_id'], ['id'])
    op.drop_column('flashcards', 'user_id')
    op.drop_column('flashcards', 'document_id')
    op.add_column('test_results', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('test_results', sa.Column('max_score', sa.Float(), nullable=False))
    op.add_column('test_results', sa.Column('submitted_answers', sa.JSON(), nullable=True))
    op.add_column('test_results', sa.Column('time_taken', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index('idx_test_result_test', table_name='test_results')
    op.drop_index('idx_test_result_user', table_name='test_results')
    op.drop_constraint('test_results_user_id_fkey', 'test_results', type_='foreignkey')
    op.create_foreign_key(None, 'test_results', 'users', ['student_id'], ['id'])
    op.drop_column('test_results', 'user_id')
    op.drop_column('test_results', 'answers')
    op.add_column('tests', sa.Column('subject', sa.String(length=100), nullable=True))
    op.add_column('tests', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tests', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('tests', 'deleted_at')
    op.drop_column('tests', 'type')
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('student_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('lecturer_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'gpa')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'lecturer_code')
    op.drop_column('users', 'student_code')
    op.drop_column('users', 'username')
    op.add_column('tests', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tests', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('tests', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('tests', 'updated_at')
    op.drop_column('tests', 'is_active')
    op.drop_column('tests', 'subject')
    op.add_column('test_results', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('test_results', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_results', type_='foreignkey')
    op.create_foreign_key('test_results_user_id_fkey', 'test_results', 'users', ['user_id'], ['id'])
    op.create_index('idx_test_result_user', 'test_results', ['user_id'], unique=False)
    op.create_index('idx_test_result_test', 'test_results', ['test_id'], unique=False)
    op.drop_column('test_results', 'created_at')
    op.drop_column('test_results', 'time_taken')
    op.drop_column('test_results', 'submitted_answers')
    op.drop_column('test_results', 'max_score')
    op.drop_column('test_results', 'student_id')
    op.add_column('flashcards', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flashcards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key('flashcards_user_id_fkey', 'flashcards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('flashcards_document_id_fkey', 'flashcards', 'documents', ['document_id'], ['id'])
    op.drop_column('flashcards', 'updated_at')
    op.drop_column('flashcards', 'set_id')
    op.add_column('documents', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('idx_document_uploader', 'documents', ['uploader_id'], unique=False)
    op.create_index('idx_document_subject', 'documents', ['subject'], unique=False)
    op.create_index('idx_document_public', 'documents', ['is_public'], unique=False)
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_path')
    op.add_column('document_shares', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_shares', sa.Column('access_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_shares', sa.Column('shared_with_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_shares', type_='foreignkey')
    op.drop_constraint(None, 'document_shares', type_='foreignkey')
    op.create_foreign_key('document_shares_shared_with_user_id_fkey', 'document_shares', 'users', ['shared_with_user_id'], ['id'])
    op.alter_column('document_shares', 'permission',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('document_shares', 'message')
    op.drop_column('document_shares', 'shared_to_id')
    op.drop_column('document_shares', 'shared_by_id')
    op.drop_column('discussions', 'updated_at')
    op.drop_column('discussions', 'is_question')
    op.create_table('quizzes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quizzes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='quizzes_creator_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='quizzes_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quizzes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_quizzes_id', 'quizzes', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('asked_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asked_by_user_id'], ['users.id'], name='questions_asked_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='questions_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('plagiarism_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_result_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('detected_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detected_by_user_id'], ['users.id'], name='plagiarism_reports_detected_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['test_result_id'], ['quiz_results.id'], name='plagiarism_reports_test_result_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plagiarism_reports_pkey')
    )
    op.create_index('ix_plagiarism_reports_id', 'plagiarism_reports', ['id'], unique=False)
    op.create_table('quiz_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='quiz_results_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='quiz_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_results_pkey')
    )
    op.create_index('ix_quiz_results_id', 'quiz_results', ['id'], unique=False)
    op.create_table('flashcard_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flashcard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_reviewed', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('difficulty_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_review', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], name='flashcard_progress_flashcard_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='flashcard_progress_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='flashcard_progress_pkey')
    )
    op.create_index('idx_flashcard_progress_user', 'flashcard_progress', ['user_id'], unique=False)
    op.create_index('idx_flashcard_progress_flashcard', 'flashcard_progress', ['flashcard_id'], unique=False)
    op.create_table('calculator_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expression', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='calculator_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='calculator_logs_pkey')
    )
    op.create_index('ix_calculator_logs_id', 'calculator_logs', ['id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='highlights_document_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='highlights_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='highlights_pkey')
    )
    op.create_index('ix_highlights_id', 'highlights', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activity_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_logs_pkey')
    )
    op.create_index('ix_activity_logs_id', 'activity_logs', ['id'], unique=False)
    op.create_table('external_searches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='external_searches_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='external_searches_pkey')
    )
    op.create_index('ix_external_searches_id', 'external_searches', ['id'], unique=False)
    op.drop_index(op.f('ix_test_questions_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_student_grades_id'), table_name='student_grades')
    op.drop_table('student_grades')
    op.drop_index(op.f('ix_flashcard_sets_id'), table_name='flashcard_sets')
    op.drop_table('flashcard_sets')
    # ### end Alembic commands ###
