"""Add all remaining models according to ERD

Revision ID: 3b1c85f767aa
Revises: 58b0ce116936
Create Date: 2026-03-21 15:12:49.796926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b1c85f767aa'
down_revision = '58b0ce116936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('calculator_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculator_logs_id'), 'calculator_logs', ['id'], unique=False)
    op.create_table('external_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_searches_id'), 'external_searches', ['id'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_table('document_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_shares_id'), 'document_shares', ['id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_id'), 'highlights', ['id'], unique=False)
    op.create_table('mindmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_mindmaps_id'), 'mindmaps', ['id'], unique=False)
    op.create_table('plagiarism_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_result_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['detected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['quiz_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plagiarism_reports_id'), 'plagiarism_reports', ['id'], unique=False)
    op.drop_index('ix_quiz_questions_id', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.add_column('documents', sa.Column('description', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('uploader_id', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('documents_uploaded_by_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploader_id'], ['id'])
    op.drop_column('documents', 'uploaded_by')
    op.add_column('questions', sa.Column('asked_by_user_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('questions', sa.Column('answer', sa.Text(), nullable=True))
    op.drop_constraint('questions_user_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['asked_by_user_id'], ['id'])
    op.drop_column('questions', 'question_text')
    op.drop_column('questions', 'user_id')
    op.drop_column('questions', 'answer_text')
    op.add_column('quiz_results', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('quiz_results', sa.Column('answers', sa.JSON(), nullable=True))
    op.drop_column('quiz_results', 'submitted_at')
    op.add_column('quizzes', sa.Column('type', sa.String(), nullable=False))
    op.add_column('quizzes', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('questions', sa.JSON(), nullable=False))
    op.add_column('quizzes', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.alter_column('quizzes', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('quizzes_created_by_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['creator_id'], ['id'])
    op.drop_column('quizzes', 'created_by')
    op.add_column('summaries', sa.Column('generated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'generated_by')
    op.add_column('quizzes', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_created_by_fkey', 'quizzes', 'users', ['created_by'], ['id'])
    op.alter_column('quizzes', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quizzes', 'duration_minutes')
    op.drop_column('quizzes', 'questions')
    op.drop_column('quizzes', 'creator_id')
    op.drop_column('quizzes', 'type')
    op.add_column('quiz_results', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('quiz_results', 'answers')
    op.drop_column('quiz_results', 'completed_at')
    op.add_column('questions', sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_user_id_fkey', 'questions', 'users', ['user_id'], ['id'])
    op.drop_column('questions', 'answer')
    op.drop_column('questions', 'content')
    op.drop_column('questions', 'asked_by_user_id')
    op.add_column('documents', sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_uploaded_by_fkey', 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'uploader_id')
    op.drop_column('documents', 'is_public')
    op.drop_column('documents', 'subject')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'description')
    op.create_table('quiz_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='quiz_questions_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_questions_pkey')
    )
    op.create_index('ix_quiz_questions_id', 'quiz_questions', ['id'], unique=False)
    op.drop_index(op.f('ix_plagiarism_reports_id'), table_name='plagiarism_reports')
    op.drop_table('plagiarism_reports')
    op.drop_index(op.f('ix_mindmaps_id'), table_name='mindmaps')
    op.drop_table('mindmaps')
    op.drop_index(op.f('ix_highlights_id'), table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_document_shares_id'), table_name='document_shares')
    op.drop_table('document_shares')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_external_searches_id'), table_name='external_searches')
    op.drop_table('external_searches')
    op.drop_index(op.f('ix_calculator_logs_id'), table_name='calculator_logs')
    op.drop_table('calculator_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
