"""Update user model for ERD compliance

Revision ID: 58b0ce116936
Revises: 7eac4f7d6d01
Create Date: 2026-03-21 15:02:54.244025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b0ce116936'
down_revision = '7eac4f7d6d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'gpa')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
