"""Remove Quiz and QuizResult tables

Revision ID: ef67499f27b7
Revises: c9dd048cd862
Create Date: 2026-03-21 15:56:17.789572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef67499f27b7'
down_revision = 'c9dd048cd862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
